services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  frontend:
    image: thuanlp/studentmanagerment_fe:latest
    container_name: frontend
    ports:
      - "5731:5731"
    networks:
      - app-network
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=http://localhost:3001

  backend:
    image: thuanlp/studentmanagerment_be:latest
    container_name: backend
    ports:
      - "3001:3001"
    networks:
      - app-network
    environment:
      - PORT=3001
      - DB_CONNECTION_STRING="mongodb://user:pass@mongodb:27017/studentmanagement?authSource=admin"
      - DB_NAME="studentmanagerment"

  volumes:
    mongodb_data:

networks:
  app-network:
    driver: bridge
